UN-OCHA/gms-site

- html/modules/custom/gms_pdflink/src/Controller/PrintSectionController.php
- html/modules/custom/gms_pdflink/src/Controller/ViewPdfController.php
> PDF image issue

- html/modules/custom/gms_ocha/gms_ocha.module
- html/modules/custom/gms_pdflink/src/Controller/PrintSectionController.php
- html/modules/custom/gms_pdflink/src/Controller/ViewPdfController.php
- html/modules/custom/html_export/html_export.module
> PDF image issue internal call

- config/block.block.ochanavigation.yml
- config/block.block.searchform.yml
- config/block.block.usermenu.yml
- config/block.block.welcometext.yml
- config/core.menu.static_menu_link_overrides.yml
- config/gms_ocha_common.settings.yml
- config/system.menu.ocha-navigation.yml
- html/themes/custom/gms_ocha_common/css/styles.css
- html/themes/custom/gms_ocha_common/gms_ocha_common.theme
- html/themes/custom/gms_ocha_common/sass/styles.scss
- html/themes/custom/gms_ocha_common/templates/cd/cd-header/cd-site-header.html.twig
- html/themes/custom/gms_ocha_common/templates/navigation/menu--ocha-navigation.html.twig
> Design update

- html/modules/custom/gms_pdflink/src/Controller/ViewPdfController.php
> Ocha Snap Update

- Makefile
- tests/docker-compose.yml
Refs: OPS-8219
Similar to https://github.com/UN-OCHA/gho-2022-site/pull/90, assuming it doesn't change anything else beyond local usage.
Also, see https://github.com/UN-OCHA/gms-stack/pull/89
> chore: Alter name of local image for consistency

- composer.lock
> Routine updates for core and contrib.

- composer.patches.json
Had an issue with this locally.
> bug: fix issue with environment indicator when not set

- .github/workflows/composer-update.yml
- composer.json
- composer.lock
- composer.patches.json
An alternative version of https://github.com/UN-OCHA/gms-site/pull/219 with the composer.lock conflict resolved.
> Update from develop

- .travis.yml
- composer.json
- composer.lock
- composer.patches.json
- symfony.lock
Refs: OPS-8943
Automatic PR failed due to a patch for environment_indicator which has since been merged. Removed google_analytics module as it's been replaced.
> chore: manual periodic update as patches failed

- html/modules/custom/gms_ocha/src/Plugin/Block/GmsCBPFBanner.php
- html/modules/custom/gms_ocha/src/Plugin/Block/GmsCERFBanner.php
I'm not sure how code that fails tests even managed to get merged, branch protection rules are set to prevent it.
> chore: Update code so the PHPCS tests pass.

- composer.lock
This includes Drupal core 9.5.2.
> chore: Update all outdated packages.

- docker/Dockerfile
> chore: update dockerfile

- docker/Dockerfile
> fix: Bump the docker image to a propoerly fixed one.

- composer.lock
- docker/Dockerfile
> Core security update

- .github/workflows/run-tests.yml
> chore: adapt tests for running locally

- composer.lock
- symfony.lock
> chore: update lock file

- config/core.entity_form_display.node.special_page.default.yml
- config/core.entity_view_display.node.special_page.default.yml
- config/core.entity_view_display.node.special_page.teaser.yml
> fix: Look at that, more domain related fields. Shoo!

- .github/workflows/run-tests.yml
> chore: add permissions so dependabot tests can pass

- .gitignore
- local/.env.example
- local/README.md
- local/docker-compose.yml
- local/exec.sh
- local/install.sh
- local/shared/settings/services.yml
- local/shared/settings/settings.local.php
> chore: add local site setup

- composer.patches.json
- config/amazon_ses.settings.yml
- config/aws.profile.amazon_ses.yml
- config/core.extension.yml
- config/mailsystem.settings.yml
* Enable the previously added modules with palceholder config.
* Patch one of them to avoid a backtrace on non-prod.
> feat: Use the new mail modules.

- PATCHES/3416368-error-not-caught-extra.patch
- PATCHES/3416368-error-not-caught-queue.patch
- PATCHES/3416368-error-not-caught.patch
- composer.patches.json
> chore: Replace the amazon_ses patch link with a set that actually applies to 3.0.1 instead of 3.0.x-dev only.

- html/modules/custom/gms_pdflink/src/Controller/ViewPdfController.php
> fix: Catch when there is no node and return access denied.

- docker/Dockerfile
Refs: OPS-10294
It's blocking the build
> fix: omit apm-agent, perhaps temporarily

- config/google_tag.container.default.yml
- docker/Dockerfile
> Include updated GTM configuration

- docker/Dockerfile
> chore: remove apm-agent permanently

- config/views.view.monitoring_sensor_results.yml
- config/views.view.search_api_page.yml
- config/views.view.search_content.yml
> chore: bring config up to date

- composer.json
- composer.lock
> chore: use supported version of social_auth_roles

- composer.patches.json
> chore: remove outdated patch

- CHANGELOG.md
- composer.json
- composer.lock
> chore: update changelog

- composer.json
- composer.lock
> chore: bump metatag module version

- composer.lock
> chore: further package updates

- CHANGELOG.md
- composer.json
- composer.lock
- config/back_to_top.settings.yml
- config/seckit.settings.yml
- tests/docker-compose.yml
* Add csp for vimeo iframes ([f5c685](https://github.com/UN-OCHA/gms-site/commit/f5c68579e57b0b3eb13313bad6bbeef89585c0a8))
* Bump metatag module version ([94374e](https://github.com/UN-OCHA/gms-site/commit/94374ec6874be72bcd1cd3239003ae4e81b87712))
* Further package updates ([f3c8d9](https://github.com/UN-OCHA/gms-site/commit/f3c8d99f37baca6d2ee1acf2860bcd6d1eec66be))
* Update all outdated drupal/* unocha/* drush/* packages. ([5fb0c6](https://github.com/UN-OCHA/gms-site/commit/5fb0c640308eb3e9bf3c6811acb2185b9efb4722), [92199e](https://github.com/UN-OCHA/gms-site/commit/92199e3b1101f02acf90c67dd989264d4d1e5d33), [934975](https://github.com/UN-OCHA/gms-site/commit/9349755c4a831604efe1e8b4f62122874bfad432), [ed7290](https://github.com/UN-OCHA/gms-site/commit/ed729037f59af16d8e1f31a6a53d8a3b …
> Deploy 19-11-2024

- composer.json
- composer.lock
> chore: remove config_filter module

- composer.json
- composer.lock
- config/core.extension.yml
- docker/Dockerfile
- docker/memcache.services.yml
> feat: Add memcache to GMS to reduce impact on mysql when being scraped.

- .github/workflows/composer-update-config.yml
- .github/workflows/composer-update.yml
> chore: Use the visible / editable maintainers var for PR assignment.

- .github/workflows/composer-update-config.yml
- .github/workflows/composer-update.yml
- composer.lock
> chore: Update main with recent routine updates for monthly deploy.
